### ISSUE TITLE
Should `<or>` and `choice` take empty lists?

### ISSUE THREAD

**Issue by greghendershott** [stchang/parsack#35]
Although easy to work-around with something like the following:

```racket
;; Parsack's <or> disallows zero elements, and `choice` uses it. So:
(define choice*
  (match-lambda
   [(list) $err]
   [(list xs ...) (choice xs)]))
```
I wanted to low-pri bug this.

The issue is actually `<or>`, for which `choice` is a wrapper: `<or>` errors if you give it `'()`.

Admittedly this isn't such a big deal for `<or>`. So what if you can't do:

```racket
(<or> #;foo)
```
and instead must do:

```racket
#;(<or> foo)
```
Not a huge deal.

However `choice` is trickier as it might get an empty list programmatically.

**Comment by stchang** [comment]
I think I merged this. Closing.
