### ISSUE TITLE
example json parser is incredible slow 

### ISSUE THREAD

**Issue by WeweTom** [stchang/parsack#38]
a sample json file , about 250k , use Node only takes `2ms` , but use parsack , it takes about   `62502ms`

**Comment by stchang** [comment]
parsack's json parsing is now comparable to Racket. Running Greg's test:

```
$ racket json-perf-test.rkt 
parsack json parser:
cpu time: 4 real time: 8 gc time: 0
Racket read-json:
cpu time: 4 real time: 3 gc time: 0
```

**Comment by WeweTom** [comment]
:+1:
