### ISSUE TITLE
Licensing unclear

### ISSUE THREAD

**Issue by taktoa** [stchang/parsack#49]
I'm interested in forking parsack and porting it to GNU Guile Scheme, but I don't see any licensing information for this project. Would it be possible to make the licensing clearer?

Thanks,
Remy Goldschmidt

**Comment by stchang** [comment]
@greghendershott @LeifAndersen @neomantic I'm going to add an LGPL license (same as Racket). Is this acceptable?

**Comment by neomantic** [comment]
That works for me.

**Comment by greghendershott** [comment]
The frog and markdown packages are MIT, so IIUC they couldn't use parsack if it is LGPL?  Therefore I'd strongly prefer MIT, if that's OK with the rest of you.

**Comment by stchang** [comment]
> The frog and markdown packages are MIT, so IIUC they couldn't use parsack if it is LGPL?

I believe MIT-licensed software can "use" LGPL software (but not GPL), [but can't modify](http://programmers.stackexchange.com/questions/141847/how-does-using-a-lgpl-gem-affect-my-mit-licensed-application). Would you consider the `parsack.rkt` file in `markdown` "derivative"?

Anyhow, I don't have a strong opinion so I will go with MIT if everyone else is ok with it.

**Comment by neomantic** [comment]
Although I always lean words the (L)GPL, I didn't contribute that much, so
I'll go with the majority.  It is, though, perfectly acceptable to
dual-license with MIT and LGPL.

**Comment by greghendershott** [comment]
@stchang I don't know. IANAL. My concern is that, even if one hired a lawyer to advise, the answer might be a lot of expensive flowery language that amounts to, "maybe; it depends". I'm exaggerating a little but I've seen that happen enough, so....

It seems like the most broadly compatible option is to use MIT, since it permits any usage by any other license. IIUC.

**Comment by greghendershott** [comment]
Oh weird timing, I typed that just as you pushed the commit. Thank you!

**Comment by LeifAndersen** [comment]
I really don't care which way we go on this. My natural inclination is (L)GPL, but I don't care.

MIT projects should be able to link to LGPL projects: http://www.gnu.org/licenses/lgpl.html

Unless I'm mistaken, having marcdown be X11/MIT licensed should not be a problem.

**Comment by LeifAndersen** [comment]
Ah, I see you licensed it under MIT, that works too.
