### ISSUE TITLE
Mongo dates

### ISSUE THREAD

**Issue by bilal68** [stchang/parsack#52]
can any one tell me how can i apply filter on mongo dates.
currently i am trying to do is this

db.getCollection("appointments").find(
    { 
        "start" : {
            "$gte" : "2019-05-20T10:00:00.000+00:00"
        },
 "start" : {
            "$lte" : "2019-05-22T10:00:00.000+00:00"
        }
    }
);

but its giving me empty result.

**Comment by greghendershott** [comment]
I think you posted this issue to the wrong repo? I'll close. (If I'm mistaken? Apologies. Feel free to reopen.)
