### ISSUE TITLE
Install parsack without documentation?

### ISSUE THREAD

**Issue by winny-** [stchang/parsack#55]
Hello, I'm opening this issue as a result of https://github.com/winny-/toml-racket/issues/4

Is there a way to install parsack without documentation?

Some projects use multiple packages.  Not sure what works best.  Here's an example https://github.com/rmculpepper/asn1 This way when somebody does `raco pkg install --auto ans1-lib` it can install deps without much build time or download time.

**Comment by stchang** [comment]
yes, this pkg should be split into the standard `-lib`, `-doc`, `-test` collections. I will work on that

**Comment by greghendershott** [comment]
One option is to follow those four-package examples -- where `parsack` would become a "meta" package that `deps` and `implies` the other three, `-lib`, `-doc`, `-test` packages. Certainly that's the most "granular". And if it's easiest for you to just crank that out, of course you should do that!

If it might be even easier for you (?), I think another good option would be: Simply add a `-lib` package, and keep the docs and tests in the main `parsack` package. I think that's a reasonable split, too, in terms of the two main use cases?

[[If you really like using `test` submodules, and the tests aren't too "heavy", then I think it's also reasonable to keep tests the `-lib`. Really, the heavy thing, the dependency chain that "pulls in the world", is the docs aspect.]]

But again, if I'm raising too many options/choices, and it's simplest just to do the four-package thing, then of course please just do that! :smile:

**Comment by stchang** [comment]
I think I managed to split everything correctly. Currently, it's in the [`split`  branch](https://github.com/stchang/parsack/tree/split) so you can try it if you wish. 

I plan to do some more testing on other pkgs to make sure I haven't broken anything,  but if everything goes smooth then I'll probably merge in a day or two.

**Comment by stchang** [comment]
Thanks @greghendershott ! Appreciate the extra info. Always open to hearing more options.

I went ahead and did the hard route, but hopefully existing pkgs will not be affected

**Comment by stchang** [comment]
I have merged the splitting and added separate packages to the Racket pkg manager. Please report any breakages here

**Comment by winny-** [comment]
toml-lib is now using parsack-lib and is much faster to install.  Thanks!
